### PR TITLE
Batch search

### PR DESCRIPTION
**Pull request by korac**
Resolving #12 
Batch search capabilities added.

New method signature added to the client instance: `batch_search(requests)`
Requests argument is an array of hashes with following attributes: `type`, `uuid` and `relationships`.

Specs added and docs updated.

Open for any constructive comments/edits; my first contribution to open source.

### CODE REVIEW

**Comment by encoreshao** [comment]
Thank you @korac for the update! Your update looks great and merged into master. 

- Really happy to have you joined!

**Comment by korac** [comment]
Awesome, thanks for the feedback @encoreshao ! 
Glad to have joined!

**Comment by korac** [comment]
Hey @encoreshao when can we expect the latest changes to be pushed up to rubygems?
Thanks!

**Comment by encoreshao** [comment]
@korac - released new version on rubygems - `crunchbase-ruby-library-0.3.2`

**Pull request merged**
